### ISSUE TITLE
Can't use intermediate CA cert.

### ISSUE THREAD

**Issue by st33v** [r509/r509#102]
I'm testing with a root CA and an intermediate cert created thusly:

```
openssl ca -keyfile private/ca.key.pem -cert certs/ca.cert.pem -extensions v3_ca -notext -md sha256 -in r509/certs/r509_ca.csr.pem -out r509/certs/r509_ca.crt.pem
```

The ca command creates the cert without error and I can verify that my intermediate CA was signed by my root ca:

```
openssl verify -CAfile /etc/pki/CA/certs/ca.cert.pem     /etc/pki/CA/r509/certs/r509_ca.crt.pem
/etc/pki/CA/r509/certs/r509_ca.crt.pem: OK
```

however, upon running rackup I get the error:
```
[root@dogtag r509]# rackup -p 9292
/usr/local/share/gems/gems/r509-0.10.0/lib/r509/cert.rb:331:in `parse_private_key': Key does not match cert. (R509::R509Error)
```

Is this the expected behavior or did I create my intermediate CA incorrectly?

**Comment by reaperhulk** [comment]
That error means the public key in the certificate and the private key you provided don't match. You'll want to pass the same private key as you used to create the CSR.

**Comment by st33v** [comment]
weird... I must have botched something when I created the Sub CA cert. Not
sure what I did. I was following the instructions here
<https://jamielinux.com/articles/2013/08/create-an-intermediate-certificate-authority/>
but yeah, I'm not able to match the modulus on that cert with either the CA
key or the Sub CA key.

thanks for your help,
--steve

**Comment by st33v** [comment]
my bad... signed the ca with the wrong key.
