### ISSUE TITLE
Missing single quote in example

### ISSUE THREAD

**Issue by yonah-codefresh** [r509/r509#104]
The file:
r509/lib/r509/cert/extensions/extended_key_usage.rb

Line 64:
        #     :value => ['clientAuth,'serverAuth']

Should probably be:
        #     :value => ['clientAuth','serverAuth']

**Comment by reaperhulk** [comment]
Thanks for the report! I'm happy to merge a PR to fix this if you want to submit it. Otherwise I can do it in a few days.
